#!/bin/bash
#BSUB -W 96:0
#BSUB -J copyCXBfiles
#BSUB -q mcore
#BSUB -o copyCXBfiles_%J.out
#BSUB -e copyCXBfiles_%J.screen
#BSUB -R 'rusage[mem=16384] span[hosts=1]'
#BSUB -n 4
#module load seq/skewer/0.1.120
module load seq/samtools/1.3
module load seq/fastqc/0.11.3
module load seq/bamtools/2.2.3
module load seq/cufflinks/2.2.1

: <<ScriptBackground
This BASH script is for the automation of 
"copying Cuffquant CXB files".
Script Author: Dr. Alex Tzuu-Wang Chang 
ScriptBackground

dtime=`date +'%F_%H%M'`
echo "The current time is $dtime"
echo "You are $USER"
# echo "The JOB-ID of this submitted shell script (BASH script) is %J"
echo "The current shell ID is $$"
echo
SourceDIR="/n/data1/hms/genetics/seidman/danny/RNASEQ/alextwc/20160912Cuffquant/transcribe"
  DestDIR="/n/data1/hms/genetics/seidman/danny/RNASEQ/alextwc/20160912Cuffquant/CXBfiles"

date && echo 'Finished setting the paths for both source and destination folders'
echo

cd $DestDIR
: > ./$USER.$dtime.$$.txt

date && echo 'Start moving CXB files to destination folder'
echo
for i in $(ls -d $SourceDIR/*/); do echo $(basename $i) >> $USER.$dtime.$$.txt; done
for line in $(cat $USER.$dtime.$$.txt)
do 
   if [ -d "$SourceDIR/$line" ] && [ -f "$SourceDIR/$line/cuffquant_out/abundances.cxb" ]; then 
       mv $SourceDIR/$line/cuffquant_out/abundances.cxb $DestDIR/$line.abundances.cxb
#      mv $SourceDIR/$line/tophat_out/unmapped.bam $unmappedDIR/$line-.unmapped.bam
#      mv $SourceDIR/$line/tophat_out/align_summary.txt $alignSummaryDIR/$line-.align_summary.txt
#      cp -r $SourceDIR/$line/cufflinks ./$line.cufflinks
#      cp $SourceDIR/$line/*.zip ./
   fi
done

echo
date && echo 'Finished'
# : > ./$USER.$dtime.$$.txt
# echo >> $USER.$dtime.$$.txt
ls -alish >> $USER.$dtime.$$.txt
